# Generated by Django 3.0 on 2019-12-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='msg',
            new_name='message',
        ),
    ]
